{% set version = "0.9.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-incadata
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/incadata_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/incadata/incadata_{{ version }}.tar.gz
  sha256: f0dddc701efa182420f41cb18d40782c44a1c159d88f88d0dc9d8d3bbffa0725

build:
  number: 4
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-backports
    - r-decoder
    - r-dplyr
    - r-rvest
    - r-sweidnumbr
    - r-xml2
  run:
    - r-base
    - r-backports
    - r-decoder
    - r-dplyr
    - r-rvest
    - r-sweidnumbr
    - r-xml2

test:
  commands:
    - $R -e "library('incadata')"           # [not win]
    - "\"%R%\" -e \"library('incadata')\""  # [win]

about:
  home: https://cancercentrum.bitbucket.io/incadata
  license: GPL-2.0-only
  summary: " Handle data in formats used by cancer centers in Sweden, both from 'INCA'  (<https://rcc.incanet.se>) and by the older register platform 'Rockan'. All\
    \ variables are coerced to suitable classes based on their format.  Dates (from various formats such as with missing month or day, with or  without century prefix\
    \ or with just a week number) are all recognized as dates and coerced to the ISO 8601 standard (Y-m-d). Boolean variables (internally stored either as 0/1 or\
    \ \"True\"/\"False\"/blanks  when exported) are coerced to logical.  Variable names ending in '_Beskrivning' and '_Varde' will be character,  and 'PERSNR' will\
    \ be coerced (if possible) to a valid personal identification  number 'pin' (by the 'sweidnumbr' package). The package also allow the user to interactively choose\
    \ if a variable should  be coerced into a potential format even though not all of its values might  conform to the recognized pattern. It also contain a caching\
    \ mechanism in order to temporarily store data sets  with its newly decided formats in order to not rerun the identification  process each time.  The package\
    \ also include a mechanism to aid the documentation process  connected to projects build on data from 'INCA'. From version 0.7, some general help functions are\
    \ also included,  as previously found in the 'rccmisc' package."
  license_family: GPL2
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: incadata
# Type: Package
# Title: Recognize and Handle Data in Formats Used by Swedish Cancer Centers
# Version: 0.8.2
# Authors@R:  c( person("Erik", "Bulow", email = "erik.bulow@rccvast.se", role = c("aut", "cre"), comment = c(ORCID = "0000-0002-9973-456X") ) )
# Description:  Handle data in formats used by cancer centers in Sweden, both from 'INCA'  (<https://rcc.incanet.se>) and by the older register platform 'Rockan'. All variables are coerced to suitable classes based on their format.  Dates (from various formats such as with missing month or day, with or  without century prefix or with just a week number) are all recognized as dates and coerced to the ISO 8601 standard (Y-m-d). Boolean variables (internally stored either as 0/1 or "True"/"False"/blanks  when exported) are coerced to logical.  Variable names ending in '_Beskrivning' and '_Varde' will be character,  and 'PERSNR' will be coerced (if possible) to a valid personal identification  number 'pin' (by the 'sweidnumbr' package). The package also allow the user to interactively choose if a variable should  be coerced into a potential format even though not all of its values might  conform to the recognized pattern. It also contain a caching mechanism in order to temporarily store data sets  with its newly decided formats in order to not rerun the identification  process each time.  The package also include a mechanism to aid the documentation process  connected to projects build on data from 'INCA'. From version 0.7, some general help functions are also included,  as previously found in the 'rccmisc' package.
# License: GPL-2
# Depends: R (>= 2.10)
# Imports: backports, decoder, dplyr, rvest, sweidnumbr, xml2
# Suggests: testthat, knitr, rmarkdown, R.rsp
# VignetteBuilder: R.rsp
# URL: https://cancercentrum.bitbucket.io/incadata
# BugReports: https://www.bitbucket.org/cancercentrum/incadata/issues
# LazyData: true
# RoxygenNote: 6.1.1
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2019-05-05 20:07:34 UTC; erikbulow
# Author: Erik Bulow [aut, cre] (<https://orcid.org/0000-0002-9973-456X>)
# Maintainer: Erik Bulow <erik.bulow@rccvast.se>
# Repository: CRAN
# Date/Publication: 2019-05-05 20:30:04 UTC
